# Generated by Django 5.0.6 on 2026-06-21 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品名')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='ブランド')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='カテゴリ')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='仕入先')),
                ('purchase_price_jpy', models.PositiveIntegerField(verbose_name='仕入価格')),
                ('expected_sale_price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='想定売価USD')),
                ('shipping_cost_jpy', models.PositiveIntegerField(verbose_name='送料')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='為替')),
                ('ebay_fee_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='eBay手数料率')),
                ('status', models.CharField(choices=[('purchased', '仕入れ済み'), ('listed', '出品中'), ('sold', '売却済み'), ('shipped', '発送済み')], default='purchased', max_length=20, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
