# Generated by Django 5.0.6 on 2026-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_ebay_fee_jpy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='実eBay手数料'),
        ),
        migrations.AddField(
            model_name='product',
            name='actual_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='実際の為替'),
        ),
        migrations.AddField(
            model_name='product',
            name='actual_sale_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='実売価格USD'),
        ),
        migrations.AddField(
            model_name='product',
            name='actual_shipping_cost_jpy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='実送料'),
        ),
        migrations.AddField(
            model_name='product',
            name='buyer_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='販売先国'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', '新品'), ('used', '中古'), ('for_parts', 'ジャンク'), ('other', 'その他')], default='used', max_length=20, verbose_name='状態'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='商品画像URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='listed_date',
            field=models.DateField(blank=True, null=True, verbose_name='出品日'),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_url',
            field=models.URLField(blank=True, verbose_name='eBay出品URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_cost_jpy',
            field=models.PositiveIntegerField(default=0, verbose_name='その他コスト'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='仕入れ日'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_shipping_jpy',
            field=models.PositiveIntegerField(default=0, verbose_name='仕入れ時送料'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_url',
            field=models.URLField(blank=True, verbose_name='仕入れ元URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipped_date',
            field=models.DateField(blank=True, null=True, verbose_name='発送日'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, verbose_name='SKU / 管理番号'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_date',
            field=models.DateField(blank=True, null=True, verbose_name='売却日'),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='追跡番号'),
        ),
    ]
