# Generated by Django 5.0.6 on 2026-06-21 12:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0002_product_actual_ebay_fee_jpy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ebay_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='eBay手数料率'),
        ),
    ]
