# Generated by Django 5.0.6 on 2026-06-22 11:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0003_alter_product_ebay_fee_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_target_profit_rate', models.DecimalField(decimal_places=1, default=Decimal('20.0'), max_digits=5, verbose_name='デフォルト目標利益率')),
                ('default_target_roi', models.DecimalField(decimal_places=1, default=Decimal('30.0'), max_digits=5, verbose_name='デフォルト目標ROI')),
                ('default_shipping_cost_jpy', models.PositiveIntegerField(default=0, verbose_name='デフォルト送料')),
                ('default_ebay_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='デフォルトeBay手数料率')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_settings', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': 'セラー設定',
                'verbose_name_plural': 'セラー設定',
            },
        ),
    ]
