# Generated by Django 5.0.6 on 2026-06-22 11:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0004_sellersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='default_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8, verbose_name='デフォルト為替'),
        ),
    ]
