# Generated by Django 5.0.6 on 2026-06-22 12:02

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


def backfill_expected_sale_price_jpy(apps, schema_editor):
    Product = apps.get_model("profittracker", "Product")
    for product in Product.objects.filter(expected_sale_price_jpy__isnull=True, expected_sale_price_usd__isnull=False):
        product.expected_sale_price_jpy = int(
            (product.expected_sale_price_usd * product.exchange_rate).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
        )
        product.save(update_fields=["expected_sale_price_jpy"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0005_sellersettings_default_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_sale_price_jpy_manual',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='実売価格JPY'),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_sale_price_jpy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='想定売価JPY'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_channel',
            field=models.CharField(choices=[('ebay', 'eBay'), ('mercari', 'メルカリ'), ('other', 'その他')], default='ebay', max_length=20, verbose_name='販売チャネル'),
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_ebay_fee_jpy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='実販売手数料'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebay_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='販売手数料率'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expected_sale_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='想定売価USD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listing_url',
            field=models.URLField(blank=True, verbose_name='販売ページURL'),
        ),
        migrations.RunPython(backfill_expected_sale_price_jpy, noop_reverse),
    ]
