# Generated by Django 5.0.6 on 2026-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0006_product_actual_sale_price_jpy_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_channel',
        ),
        migrations.AddField(
            model_name='product',
            name='actual_sales_channel',
            field=models.CharField(blank=True, choices=[('ebay', 'eBay'), ('mercari', 'メルカリ'), ('yahoo_auction', 'ヤフオク'), ('rakuma', 'ラクマ'), ('other', 'その他')], max_length=20, verbose_name='売れたチャネル'),
        ),
    ]
