# Generated by Django 5.0.6 on 2026-06-23 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0007_remove_product_sales_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='long_inventory_days',
            field=models.PositiveIntegerField(default=90, verbose_name='長期在庫日数'),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='loss_cut_days',
            field=models.PositiveIntegerField(default=60, verbose_name='損切り候補日数'),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='low_profit_rate',
            field=models.DecimalField(decimal_places=1, default=Decimal('15.0'), max_digits=5, verbose_name='低利益率判定'),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='markdown_ok_days',
            field=models.PositiveIntegerField(default=30, verbose_name='値下げ余地あり日数'),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='markdown_review_days',
            field=models.PositiveIntegerField(default=45, verbose_name='値下げ検討日数'),
        ),
    ]
