# Generated by Django 5.0.6 on 2026-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profittracker', '0008_sellersettings_long_inventory_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='brand_keywords',
            field=models.TextField(blank=True, default='Hermès\nBottega Veneta\nLouis Vuitton\nYves Saint Laurent\nSaint Laurent\nMaison Margiela\nComme des Garçons\nDolce & Gabbana\nPorter\nSeiko\nCanon', verbose_name='ブランド自動入力辞書'),
        ),
    ]
